[package]
name = "jukebox-playlist-random"
version = "0.1.0"
edition.workspace = true

[dependencies]
jukebox-playlist = { path = "../jukebox-playlist" }
jukebox-library = { path = "../jukebox-library" }
