[package]
name = "jukebox-library-file"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytes = { workspace = true }
jukebox-library = { path = "../jukebox-library" }
jukebox-decoder = { path = "../jukebox-decoder" }
rand = "0.9.0"
tokio = { workspace = true }
