[package]
name = "jukebox-rs"
version = "0.1.0"
edition = { workspace = true }


[dependencies]
actix-web = "4.10.2"
bytes = "1.10.1"
pin-project = "1.1.10"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
